<?php

/**
 * @file
 * Display user social river.
 * based on the excellent jQuery plugin by christianv (Christian Vuerings)
 * https://github.com/christianv/jquery-lifestream
 */

/**
 * Implements hook_perm().
 */
function social_river_perm() {
  return array('administer social river', 'view social river');
}


/**
* Add CSS and JS Files needed for displaying the river
*/
function _social_river_add_scripts() {
  drupal_add_js(drupal_get_path('module', 'social_river') . '/js/jquery.lifestream.js');
  drupal_add_js(drupal_get_path('module', 'social_river') . '/js/jquery.timeago.js');
}

/**
* Return code of a wall
*/
function _social_river_get_river_code($uid) {

  $output = '';
  if(!user_access('view social river')) return $output;

  drupal_add_css(drupal_get_path('module', 'social_river') . '/css/lifestream.css');

  $output .= "<link href=\"".drupal_get_path('module', 'social_river')."/css/lifestream.css\" rel=\"stylesheet\" type=\"text/css\"><div id=\"social_river_".$uid."\">&nbsp;</div><script type=\"text/javascript\">
    (function(){
      var count = 0,
      list = [
        {
          service: 'delicious',
          user: 'denbuzze'
        },
        {
          service: 'github',
          user: 'christianv'
        },
        // Run javascript:alert(userid); when you're logged in at stackoverflow
        {
          service: 'stackoverflow',
          user: '117193'
        },
        {
          service: 'tumblr',
          user: 'hiromitz'
        },
        {
          service: 'twitter',
          user: 'jq_lifestream'
        }
      ];

      Date.prototype.toISO8601 = function(date) {
          var pad = function (amount, width) {
              var padding = '';
              while (padding.length < width - 1 && amount < Math.pow(10, width - padding.length - 1))
                  padding += '0';
              return padding + amount.toString();
          }
          date = date ? date : new Date();
          var offset = date.getTimezoneOffset();
          return pad(date.getFullYear(), 4)
              + '-' + pad(date.getMonth() + 1, 2)
              + '-' + pad(date.getDate(), 2)
              + 'T' + pad(date.getHours(), 2)
              + ':' + pad(date.getMinutes(), 2)
              + ':' + pad(date.getUTCSeconds(), 2)
              + (offset > 0 ? '-' : '+')
              + pad(Math.floor(Math.abs(offset) / 60), 2)
              + ':' + pad(Math.abs(offset) % 60, 2);
      };

      $('#social_river_".$uid."').lifestream({
        limit: 400,
        list: list,
        feedloaded: function(){
          count++;
          // Check if all the feeds have been loaded
          if( count === list.length ){
            $('#social_river_".$uid." li').each(function(){
              var element = $(this),
                  date = new Date(element.data('time'));
              element.append(' <abbr class=\"timeago\" title=\"' + date.toISO8601(date) + '\">' + date + \"</abbr>\");
            })
            $('#social_river_".$uid." .timeago').timeago();
          }
        }
      });
      
    })();
  </script>";

  return $output;
}